version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"

  backend:
    build:
      context: ./Backend
    ports:
      - "8000:8000"
    environment:
      FLASK_APP: app.py
